import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { CustomThemeProvider } from "@/hooks/DarkmodeProvider";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "sonner";
import Navbar from "@/components/navbar-section/Navbar";
import { Divider } from "@mui/material";
import HeaderSection from "@/components/header-section/HeaderSeaction";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "ShopPilot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
          {/* Toast Notification */}
          <Toaster
            richColors
            position="top-right"
            toastOptions={{
              style: {
                zIndex: 9999,
                top: '4.5rem',
                right: '5rem',
              },
            }}
          />
          
          <CustomThemeProvider>
            <CartProvider>
              <header className="w-full sticky top-0 z-20">
                <HeaderSection />
                <Divider className="w-full h-[1px] bg-gray-200/70 dark:bg-gray-700" />
                <Navbar />
              </header>
              <main>{children}</main>
            </CartProvider>
          </CustomThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
